=== lolouk/ECML/SequenceOfActivity.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT sequenceOfActivity (activity*)>
<!--PRACTICE_ALONE = "PI"
	PRACTICE_WITH_ACCOMPANIMENT = "PA"
	CHECK_WITH_YOUR_TEACHER = "C"
	READING_OF_NOTES = "R"
	SPEED_GAME = "S" -->
	

<!ELEMENT activity (duration, tempo, songsList, gameLevel)>
<!ATTLIST activity type (PI|S|R|C|PA) #REQUIRED>

<!ELEMENT duration (#PCDATA)>
<!ELEMENT tempo (#PCDATA)>


<!ELEMENT songsList (song1, song2,song3)>
	<!ELEMENT song1 (#PCDATA)>
	<!ATTLIST song1 title CDATA #IMPLIED>
	<!ELEMENT song2  (#PCDATA)>
	<!ATTLIST song2 title CDATA #IMPLIED >
	<!ELEMENT song3 (#PCDATA)>
	<!ATTLIST song3 title CDATA #IMPLIED>


<!ELEMENT gameLevel (#PCDATA)>

=== lolouk/ECML/SequenceOfActivity.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sequenceOfActivity SYSTEM "SequenceOfActivity.dtd" >
<sequenceOfActivity>
    <activity type="PA">
        <duration>60</duration>
        <tempo>250</tempo>
        <songsList>
            <song1 title="Habanera from Carmen"></song1>
            <song2 title="To a Wild Rose"></song2>
			<song3 title="Elegy in E minor"></song3>
        </songsList>
        <gameLevel>2</gameLevel>
    </activity>
    
        <activity type="PI">
        <duration>20</duration>
        <tempo>100</tempo>
		 <songsList>
            <song1 />
            <song2 />
			<song3 />
        </songsList>
        <gameLevel>2</gameLevel>
    </activity>
    
    <activity type="S">
        <duration>20</duration>
        <tempo>250</tempo>
        <songsList>
            <song1 title="Habanera from Carmen"></song1>
            <song2 title="To a Wild Rose"></song2>
			<song3 title="Elegy in E minor"></song3>
        </songsList>
		<gameLevel>2</gameLevel>
    </activity>
    
</sequenceOfActivity>
